### ISSUE TITLE
AWS: auto-detect region for volume snapshot locations

### ISSUE THREAD

**Issue by realdimas** [vmware-tanzu/velero-plugin-for-aws#12]
While documentation mentions (https://github.com/heptio/velero/blob/bb12cbd/site/docs/master/api-types/volumesnapshotlocation.md#config) region autodetection for EBS snapshots:
> ... Queried from the AWS S3 API if not provided

it doesn't seem to be implemented: https://github.com/heptio/velero/blob/bb12cbd2d7d8f9f5dcd20583842653eca893f2cd/pkg/cloudprovider/aws/volume_snapshotter.go#L75-L79

As a result Backups against [AWS] VolumeSnapshotLocation without `spec.config.region` fails:
`level=error msg="Error getting volume snapshotter for volume snapshot location" backup=velero/XXX error="rpc error: code = Unknown desc = missing region in aws configuration" error.file="/go/src/github.com/heptio/velero/pkg/cloudprovider/aws/volume_snapshotter.go:75" error.function="github.com/heptio/velero/pkg/cloudprovider/aws.(*VolumeSnapshotter).Init" group=v1 logSource="pkg/backup/item_backupper.go:410" name=XXX namespace= persistentVolume=XXX resource=persistentvolumes volumeSnapshotLocation=default`

The issue seems to be a result of copy-paste of the documentation from BackupStorageLocation which does support autodetection of AWS region thanks to vmware-tanzu/velero#455.

While working auto-detection for EBS volume snapshot location would be ideal, the first step should be an update to documentation and, ideally,  validation for this field in the case when `provider=aws`.

Many thanks for a wonderful open-source product and with good UX ❤️

**Comment by sebastialonso** [comment]
Hi. I'm having exactly this issue. Is there a practical way to bypass it? Am I missing the region field in a config file?

Thanks!

**Comment by skriss** [comment]
@sebastialonso you need to specify the `region` field under `spec.config` for your `VolumeSnapshotLocation`.

**Comment by sebastialonso** [comment]
@skriss Thank you for your answer!

Is this the same as passing the `--snapshot-location-config` flag to `velero install`?

**Comment by sebastialonso** [comment]
I managed to advance a little bit, but I got another problem. I'll open a new issue.

**Comment by alexcpn** [comment]
> @skriss Thank you for your answer!
> 
> Is this the same as passing the `--snapshot-location-config` flag to `velero install`?
> 
> EDIT: It should be the same, according to the link provided.

No, even giving this region in velero install I was getting the same error and was getting backup as Partially Failed. Had to edit the VolumeSnapshotlocation resource  (https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/master/volumesnapshotlocation.md ) manually to get it working

**Comment by carlisia** [comment]
Thanks for extending the install documentation @alexcpn. Seems https://github.com/vmware-tanzu/velero/pull/2799 clarifies this issue, so I'm closing it.
