### ISSUE TITLE
Pre-signed URLs don't work with port in backup-location-config s3Url param on AWS

### ISSUE THREAD

**Issue by jeniawhite** [vmware-tanzu/velero-plugin-for-aws#13]
**What steps did you take and what happened:**
I'm trying to use the backup feature on AWS endpoint.

Steps:
1) I've used velero v1.0.0 (https://github.com/heptio/velero/releases/tag/v1.0.0)

2) Ran the following installation:
```
velero install --provider aws --bucket BUCKET_NAME --backup-location-config region=AWS_REGION,s3ForcePathStyle="true",s3Url=http://AWS_URL --secret-file ./CREDENTIALS_FILE  --use-volume-snapshots=false
```

With ```AWS_URL = s3.AWS_REGION.amazonaws.com:PORT```

3) Ran the following backup command:
```
velero backup create BACKUP_NAME
``` 

The backup did not work.

**What did you expect to happen:**
I've expected for the process to run correctly and backup my data.

**Anything else you would like to add:**
I can see that velero uses the AWS S3 Go SDK and Go HTTP modules to handle the S3 requests. 
Valero backup generates an AWS S3 signedURL and uses the **AWS_URL** as host signed header but without the **PORT**.
Then velero uses the Go HTTP module to send a GET request with the presignedURL that was created by the AWS S3 SDK.
It looks like this:
```
GET /velero/backups/FOLDER/logs.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=S3_ACCESS_KEY%2F20190623%2FREGION%2Fs3%2Faws4_request&X-Amz-Date=20190623T111539Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=3beeddaa6811fb5b61c29d3597510b1d8887ba1d5f1a31e5f1bb919669956347 HTTP/1.1
Host: AWS_URL
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip

```
Notice that in the **Host** header it uses the original **AWS_URL** with the **PORT** included. But the presignedURL was signed with **AWS_URL** with the **PORT** excluded.
This results in an AccessDenied because of SignatureMismatch.
If I change the triggered request's **Host** header to value of **AWS_URL** with the **PORT** excluded this request will work and pass the Signature tests.

Velero should be consistent with the requests and preparation of the signedURL.

If you need any additional info, please feel free to contact. 
Thank you.

**Environment:**

- Velero version v1.0.0 (https://github.com/heptio/velero/releases/tag/v1.0.0)
- Kubernetes version v1-14-0 (https://kubernetes.io/docs/setup/release/notes/#v1-14-0)
- Cloud provider or hardware configuration: Macbook Pro 15 inch 2018
- OS (e.g. from `/etc/os-release`): MacOS Mojave v10.14.5

**Comment by carlisia** [comment]
I am going to close this issue for now. If it is still a problem, we can reopen.
