### ISSUE TITLE
Document permission needed for Velero when dealing with AWS encrypted resources

### ISSUE THREAD

**Issue by egagala** [vmware-tanzu/velero-plugin-for-aws#15]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

When AWS S3 buckets, EBS volumes and snapshots are encrypted and KMS is in use additional permissions are needed for Ark IAM policy. Without it either backup or restore will fail. To be specific:

- "kms:GenerateDataKey" is needed to backup data in the encrypted data bucket
- "kms:Decrypt" is needed for restore data from bucket
- "kms:ReEncryptTo"/ "kms:ReEncryptFrom" is needed to restore volume from encrypted snapshot

The easiest way to observe such requirements is to use AWS CloudTrail logs for heptio ark and see error codes produced there.

**What did you expect to happen:**

Please test it in AWS secured environment and document at heptio ark github pages

**Comment by AlexMorreale** [comment]
Are there any untested permissions i could test with? Getting some 403s putting the object.

**Comment by carlisia** [comment]
I think the documentation added here will take care of this: https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/46c18b341f0dcfba468c2b5c254e3eb310defec0/backupstoragelocation.md#backup-storage-location.

If this remains an issue, please reopen. Thanks.
