### ISSUE TITLE
What's the license of plugin?

### ISSUE THREAD

**Issue by innobead** [vmware-tanzu/velero-plugin-for-aws#21]
Is there any plan to have a LICENSE file to claim this plugin or other Velero plugins usage? Thanks.

Ref: As per the license comment declaration in code as below, this project should be under Apache License 2.

https://github.com/vmware-tanzu/velero-plugin-for-aws/blob/46d9118173f8573e237ab4cc94c2e6ed83994396/velero-plugin-for-aws/object_store.go#L8

**Comment by skriss** [comment]
good call, we need to add a LICENSE file to each of these repos. Apache 2 is correct.

**Comment by innobead** [comment]
Thanks!
