### ISSUE TITLE
Restore ALB Ingress Resource in Target Cluster with Different Security Groups

### ISSUE THREAD

**Issue by svenmueller** [vmware-tanzu/velero-plugin-for-aws#57]
Hi,

Is there an option, a recommended way or best practice how to migrate AWS ALB ingress resources in case the target cluster uses different ALB security groups?

Currently all restored AWS ALB ingress resources would need to be changed manually when restoring the ingress resource in the target cluster:

```
# annotation in source cluster
alb.ingress.kubernetes.io/security-groups: sg-xxxxxxxxxxxxx
-> 

# annotation in target cluster
alb.ingress.kubernetes.io/security-groups: sg-yyyyyyyyyyyyy
```

Any thoughts?

Thx a lot,
Sven

**Comment by dsu-igeek** [comment]
We do not have official recommendations, this would be a good thing to ask the Velero community on the #velero channel (https://kubernetes.slack.com/messages/velero) on the Kubernetes Slack server or in the Google Group (https://groups.google.com/g/projectvelero).
