### ISSUE TITLE
The velero-plugin-for-aws does not support signer version 2 ?

### ISSUE THREAD

**Issue by jinxinxin163** [vmware-tanzu/velero-plugin-for-aws#61]
I see that the velero-plugin-for-aws does not support signer version 2.
If i want to porting to support version 2, how should i DO ?
thank you .

**Comment by nrb** [comment]
@jinxinxin163 What object storage are you using that requires a signature of v2? Per Amazon, the SDK doesn't support this https://aws.amazon.com/blogs/aws/amazon-s3-update-sigv2-deprecation-period-extended-modified/.

Velero uses signature version 4 and we'd recommend users upgrade.
